name: Integration Tests (Manual)

on:
  workflow_dispatch:  # Manual trigger only
  # Note: Integration tests require full systemd support in Docker,
  # which doesn't work reliably in standard GitHub Actions runners.
  # Run these tests locally using: cd tests/integration && ./run_all_tests.sh

permissions:
  contents: read

jobs:
  integration-test:
    name: Systemd Integration Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build integration test image
      run: |
        cd tests/integration
        docker build -f Dockerfile.systemd -t systemd-monitor-test ../../

    - name: Run integration test
      run: |
        docker run --rm \
          --privileged \
          -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
          systemd-monitor-test

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-logs
        path: |
          /tmp/systemd_monitor_integration.log
          /tmp/monitor_stdout.log
        if-no-files-found: ignore
